### ISSUE TITLE
Transition speed issue 

### ISSUE THREAD

**Issue by van-cosmo** [techlab/jquery-smarttab#1]
Thanks for this tiny great plugin!
My issue is that tweaking the 'transition speed' value does not seems to work.
Here the example I tweak from downloaded pack.

```
$('#tabs').smartTab({
     autoProgress: false, stopOnFocus:true, transitionEffect:'vSlide',
     transitionSpeed:'5400' // from default 400 to  5400
});
```

Thanks
Rex

**Comment by techlab** [comment]
There is a mistake in the example and in default setting.
the transition speed should set as a number not as a string, ie without quotes.
so please set it as following, sorry for the delay

```
$('#tabs').smartTab({
   autoProgress: false, stopOnFocus:true, transitionEffect:'vSlide',
   transitionSpeed: 5400 // from default 400 to  5400
});
```
