### ISSUE TITLE
Multiple smarttabs on same page

### ISSUE THREAD

**Issue by VestigiaLunae** [techlab/jquery-smarttab#22]
Hi, I was trying to implement multiple smarttab divs on one page at once, but it didn't seem to work, as only the smarttab on the first horizontal tab worked. I was trying to make a page with plain horizontal tabs that each include a smarttab(like the screenshot below). Is this kind of feature possible?

<img width="1373" alt="Screen Shot 2022-09-02 at 8 38 36 AM" src="https://user-images.githubusercontent.com/88144173/188030155-4365593a-7925-4bcd-b05d-3d5317476530.png">
<img width="1373" alt="Screen Shot 2022-09-02 at 8 38 46 AM" src="https://user-images.githubusercontent.com/88144173/188030166-ff7e86c1-cb54-4ef7-b04d-49108ac2d5f4.png">

**Comment by techlab** [comment]
Please see the example here: http://techlaboratory.net/projects/demo/jquery-smart-tab/v4/multiple#tab-1
and code example: https://github.com/techlab/jquery-smarttab/blob/master/examples/multiple.html
