### ISSUE TITLE
jquery 3.4x seems  to break this

### ISSUE THREAD

**Issue by jpgateaux** [techlab/jquery-smarttab#4]
tried w/ jQ 3.4 wouldn't work
changed it back to 3.3.1 and everything is fine

**Comment by techlab** [comment]
Thank you @jpgateaux for reporting that. 
The plugin is update to new version v3.0.0 and now support up to the latest  jQuery-3.5.0

**Comment by jpgateaux** [comment]
thanx



Powered by Cricket Wireless



-------- Original message --------
